// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sampleDotNet8Shop.ShopUI.Models;

#nullable disable

namespace sampleDotNet8Shop.ShopUI.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20240128105841_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sampleDotNet8Shop.ShopUI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Mobile",
                            Description = "This is a IOS Phone And Create By Apple",
                            Name = "Apple IPhone 14 ProMax",
                            Price = 70000000
                        },
                        new
                        {
                            Id = 2,
                            Category = "Mobile",
                            Description = "This is a Android Phone And Create By Sumsung",
                            Name = "Sumsung Galexy S24 ultra",
                            Price = 45000000
                        },
                        new
                        {
                            Id = 3,
                            Category = "Mobile",
                            Description = "This is a Android Phone And Create By Xiaomi",
                            Name = "Xiaomi ME14 Ultra",
                            Price = 40000000
                        },
                        new
                        {
                            Id = 4,
                            Category = "Mobile",
                            Description = "This is a Android Phone And Create By Realme",
                            Name = "Realme C13 Ultra",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 5,
                            Category = "Laptop",
                            Description = "The AMD-equipped Asus Zenbook 13 OLED is currently our top recommendation for a great budget laptop",
                            Name = "Asus Zenbook 13 OLED",
                            Price = 35000000
                        },
                        new
                        {
                            Id = 6,
                            Category = "Laptop",
                            Description = "The Dell XPS 15 is our current pick for best Windows laptop overall",
                            Name = " Dell XPS 15 OLED",
                            Price = 40000000
                        },
                        new
                        {
                            Id = 7,
                            Category = "Laptop",
                            Description = "The MacBook Air M2 is the best laptop for the money",
                            Name = "Macbook Air M2",
                            Price = 50000000
                        },
                        new
                        {
                            Id = 8,
                            Category = "PC",
                            Description = "The 24-inch iMac is especially well-suited as a family computer or if you want something other than a laptop to easily move from room to room",
                            Name = "Apple iMac M3(2024)",
                            Price = 20000000
                        },
                        new
                        {
                            Id = 9,
                            Category = "PC",
                            Description = "While we like all-in-ones for their convenience, they're not easy to upgrade (if they can be at all)",
                            Name = "Dell XPS 8960 Desktop",
                            Price = 16000000
                        },
                        new
                        {
                            Id = 10,
                            Category = "PC",
                            Description = "If you're dissatisfied with the lack of configuration options available for prebuilt gaming desktops",
                            Name = "Origin PC 5000T",
                            Price = 12000000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
